.catalog:
  name: "Letschat"
  version: "1.0-node1"
  description: "Lets Chat with Mongo"
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
mongo-cluster:
  scale: 3  
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"
